### ISSUE TITLE
TF flag emulation

### ISSUE THREAD

**Issue by ghaerr** [mfld-fr/emu86#26]
Hello @mfld-fr,

I thought you might be interested in this statement from the IBM PC AT Technical Reference manual, compatibility section (2nd bullet point):
<img width="939" alt="Screen Shot 2020-12-07 at 9 07 40 AM" src="https://user-images.githubusercontent.com/11985637/101374791-dddf7f00-386b-11eb-8b7c-f46fd147fa65.png">
It seems to say that the 80286 CPU in the PC/AT does not perform a trace (TF flag) interrupt on the INT instruction, but that the processor used in the IBM PC/XT *does* interrupt on the INT instruction when the TF flag is set.

Currently, EMU86 does *not* trace through INT, as it resets TF flag on execution, correct? I present this for informational and discussion purposes only.

Thank you!

**Comment by mfld-fr** [comment]
Mmm... I has always read in the various datasheets or models that the TF flag is reset upon interruption (HW or SW), in order to forbid any automatic INT1 **inside** the interrupt handling.

This is also the observed behavior of a real CPU (= 80188 clone) used in my SBC, through the MON86 handling of INT1 & INT3 for CPU-assisted debugging, and covered by a unit test (latest steps in the [test sequence](https://github.com/mfld-fr/mon86/blob/master/test-mon86-in.txt)).

In EMU86, I implemented the trace condition as described in many 8086 models : INT1 occurs **after** the instruction only if the TF flag was set **before** that instruction and is still set **after** that instruction.

It means that INT1 does not occur just after entering the handler (= after executing INT), and does not occurs just after exiting the handler (= after executing IRET). In other words, only the interrupted code is traced, not any handler code.

**Comment by mfld-fr** [comment]
The word 'trace' could be confusing.

For example, in one 80188 document from my library, 'TF' stands for 'Trap Flag', while in another 80186 document, 'TF' stands for 'Single Step Flag'. Some of us call it the 'Trace Flag'.

The right name would be 'Trap Flag', as the INT1 is triggered synchronously **after** an instruction. The IBM document points out that depending on the CPU model, that trap does occur after returning from an INT with a 8086 (so after executing the IRET), while it does not occur with a 80186, and that could impact the 'tracing' when using INT1 in a debugger to display the next instruction.

EMU86 emulates the 80186 behavior, for the MON86 test to pass on both the emulated CPU and the real 80188 clone. I am not sure it would also pass on a real 8086 ?

EMU86 'tracing' is quite different : while the CPU trap occurs **after** executing the instruction, EMU86 displays the next instruction **before** executing it.

**Comment by ghaerr** [comment]
Agree on the difference between trap and trace, and thank you for your comments.

I think what this early IBM document is saying is that there is a difference between the trap operation in the 80286 vs the IBM PC XT's processor, which was an 8088. What I am guessing, but have not confirmed, is the early 8088 processor executed a trap on INT instructions, then Intel realized its mistake and changed that behavior when developing the protected mode 80286 (or possibly even the 8086) where, for more sophisticated operating systems, this difference is very useful.

Note that the first bullet point in the IBM document also documents an internal change for "PUSH SP" between the processors, likely also an architecture bug fix realized later by Intel. It seems the divide by zero exception was also fixed.

In any case, I think EMU86's current behavior is proper, as almost all processors these days would have the later corrected architecture behavior. It would be interesting to know whether the 8086 differs from the early 8088's (or for that matter later 8088's) in the trap operation, but I've not been able to find any specific documentation on that.

**Comment by mfld-fr** [comment]
Well, until these differences cause a trouble for some specific cases, I also think we should keep the current behavior as is.

Anyway, these are some tricky points we should keep in mind when designing the emulator, so thanks for creating this issue that could be referred later.
