### ISSUE TITLE
Add graphical console using SDL

### ISSUE THREAD

**Issue by mfld-fr** [mfld-fr/emu86#32]
Staging branch is https://github.com/mfld-fr/emu86/tree/sdl.

**Comment by mfld-fr** [comment]
@ghaerr : today the redirection in the BIOS stub from INT 10h / 16h to the EMU86 'stdio' console or a PTY console is specific to ELKS target, and brings some confusion between 'console' and 'serial port' emulation. Could the things be made clearer by connecting directly the INT 10h / 16h to a 'console' part (backend options: none / curses / SDL), and connect the INT 14h to a 'serial' part (backend options: none / stdio / PTY), and let ELKS makes the choice of the system console (BIOS console / direct console / BIOS serial / direct serial) ?

**Comment by mfld-fr** [comment]
I am currently reorganizing the code to make the 'device' / 'backend' mapping more clear, and I will open an MR soon to discuss the new layout proposal.

**Comment by mfld-fr** [comment]
From the discussion in #33, what remains to do to complete this issue:

- [ ] Add the virtual serial port device to character backend mapping (a.k.a. `serial-char.c`)
- [ ] Use the emulated memory as the SDL pixels buffer
- [ ] Rework the main loop (to be detailed)
- [ ] Non-regression test for the ELKS target (@ghaerr)
- [ ] Non-regression test for the Advantech target (@mfld-fr)
- [ ] Merge `sdl` to `master` (@mfld-fr)

**Comment by ghaerr** [comment]
@mfld-fr: Quick testing of new version has compile error on renamed "sdl_close", when built for ELKS/sdl backend. ELKS/stdio backend working. I'm not quite setup for PR, can you add the following, which fixes compile error. After this, SDL backend working with ELKS. May need tuning based on main loop, that will come later.
```
diff --git a/con-sdl.c b/con-sdl.c
index 4d246d7..5a04892 100644
--- a/con-sdl.c
+++ b/con-sdl.c
@@ -53,7 +53,7 @@ int con_get_key (word_t * k)
        *k = 0;
        ret = sdl_readkbd(&mwkey, &scancode);
        if (ret == KBD_QUIT) {
-               sdl_close();
+               con_term();
                exit(0);
        }
```

**Comment by mfld-fr** [comment]
Oup's ! Fixed in latest commit.

**Comment by ghaerr** [comment]
OK - ELKS non-regression tests PASS after last commit for both sdl and stdio backends. We are probably OK with merge into master, after which I can work on "Use the emulated memory as the SDL pixels buffer" and possible tuning for SDL backend in main loop. Main loop reworkings discussed in separately can likely also be done after merge, to keep things organized. NOTE: I have not tested "hw" serial emulation.

**Comment by mfld-fr** [comment]
Nice ! So let me push that nice enhancement to the `master` branch.

**Comment by ghaerr** [comment]
@mfld-fr: thanks for all the work getting the SDL enhancement integrated with master.

I checked again after merge and working OK.

Other items remaining to do:
- Move command line processing out of main loop (and for other reasons discussed). After that we should have discussion on "dual" sdl/stdio requirement for controlling emulator via stdio but using sdl console output. Suggest opening seperate issue to track this.
- Testing emscripten by running EMU86 in a browser. (@ghaerr)
- Using emulated memory at 0xB800 as SDL pixel buffer (@ghaerr), will likely do after other items complete.
- Various emscripten/\#ifdef cleanups (@ghaerr).

**Comment by mfld-fr** [comment]
What is the purpose of the following code block in the main loop ?
```
#ifdef __EMSCRIPTEN__
	if (++mainloop_count >= MAINLOOP_TIMER)
		{
		emscripten_sleep(1);
		mainloop_count = 0;
		}
#endif
```

**Comment by ghaerr** [comment]
> What is the purpose of the following code block in the main loop ?

Describing this is a bit complicated. 

Long story short, the Emscripten port of EMU86 compiles the emulator into web assembly (WASM), and uses a special, complex ASYNCIFY conversion process [described here](https://emscripten.org/docs/porting/asyncify.html) (and specially described [here under New Asyncify](https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html)) to convert synchronous procedure calls into asynchronous callbacks. This is required because in all browsers, all WASM and Javascript code ends up being executed as callbacks, called when the browser isn't doing other things.

So, instead of rewriting the entire EMU86 as a callback function, I use the ASYNCIFY compile option (`CC = emcc -s ASYNCIFY -O3 --emrun -s USE_SDL=2 -DSDL=1`) which ends up building a structure such that the main loop function `mainloop` is called once as a callback, then exits using the `emscripten_sleep` function. This is all magic and works using the asyncify 'normal', 'unwinding' and 'rewinding' stacks built using the BinaryEn recompiler. In some sense, the `mainloop` function is the callback.

Thus, for now, this is by far the easiest method of getting EMU86 running as an asynchronous callback within a browser. Ultimately, the special requirement is that the EMU86 main loop be callable from within the exterior `while(1)` loop using the special stack unwind/rewind mechanisms.

I think we can wrap the above code segment into a single function and place it elsewhere for cleanup, but I will have to check and test with the stack unwind/rewind code to make sure it works.

I hope this makes sense!

**Comment by ghaerr** [comment]
```
if (++mainloop_count >= MAINLOOP_TIMER)
```
The purpose of this check is to speed up the emulation considerably, by emulating multiple instructions per browser async callback.

**Comment by mfld-fr** [comment]
OK got it, thanks for the explanation !

**Comment by mfld-fr** [comment]
Well, I think we are done for the biggest part, a.k.a. adding the SDL console while keeping the other things right. More cleanup and tuning could be performed in later steps, so we can can close this issue.
